import { FloodFill2D } from './FloodFill2D';
import type { Grid2D, Point } from './FloodFill2D';

/**
    * possible gravity directions for the board
    *
    * 'down'  tiles fall towards increasing row index
    * 'up'    tiles fall towards decreasing row index
    * 'left'  tiles slide towards decreasing column index
    * 'right' tiles slide towards increasing column index
*/
export type SameGameGravity = 'down' | 'up' | 'left' | 'right';

/**
    * gameplay mode of the board
    *
    * 'normal'
    * removed tiles disappear permanently and empty lines are compacted
    *
    * 'endless'
    * removed tiles are replaced by new tiles generated by the generator
*/
export type SameGameMode = 'normal' | 'endless';

/**
    * comparator used to determine whether two tiles belong
    * to the same region
    *
    * the comparator receives two tile values (or null)
    * and must return true if they are considered equal.
*/
export type SameGameComparator<T> = (a: T | null, b: T | null) => boolean;

/**
    * identifies a single cell on the SameGame board
    *
    * row index of the cell (vertical position in the grid)
    * col column index of the cell (horizontal position in the grid)
*/
export interface SameGamePosition {
    row: number;
    col: number;
}

/**
    * statistics describing the current board state
    *
    * tiles         number of non-empty tiles currently on the board
    * empty         number of empty cells (null tiles)
    * regions       list of all removable regions (each region is a list of points)
    * largestRegion size of the largest removable region
*/
export interface SameGameBoardStats {
    tiles: number;
    empty: number;
    regions: SameGamePosition[][];
    largestRegion: number;
}

/**
    * describes all changes applied to the board after a move
    *
    * removed: tiles cleared from the board
    * moved: tiles shifted due to gravity
    * shifted: entire rows/columns moved during compaction
    * spawned: new tiles generated (endless mode)
*/
export interface SameGameBoardChange<T> {
    removed: {
        at: SameGamePosition;
        value: T;
    }[];
    moved: {
        from: SameGamePosition;
        to: SameGamePosition;
        value: T;
    }[];
    shifted: {
        from: SameGamePosition;
        to: SameGamePosition;
        value: T;
    }[];
    spawned: {
        at: SameGamePosition;
        value: T;
    }[];
}

/**
    * headless SameGame engine for grid-based puzzle games
    *
    * this class implements the core mechanics of the classic SameGame:
    * tiles of the same type that are orthogonally connected form regions
    * that can be removed together.
    *
    * features:
    * - generic tile type (T)
    * - flood-fill region detection
    * - dynamic gravity (down, up, left, right)
    * - normal or endless gameplay modes
    * - board compaction and refill
    * - region queries and solver helpers
    *
    * the engine is headless: it contains no rendering or animations
    * and is designed to be integrated into any game framework.
    *
    * typical usage:
    *
    * const game = new SameGame<number>(
    *     8,
    *     8,
    *     'down',
    *     'normal',
    *     () => Math.floor(Math.random() * 5),
    *     true
    * );
*/
export class SameGame<T> {
    private grid: Grid2D<T | null>;
    private rows: number;
    private cols: number;
    private gravity: SameGameGravity;
    private mode: SameGameMode;
    private generator: () => T;
    private equals: SameGameComparator<T>;
    private flood: FloodFill2D<T | null>;

    /**
        * creates a SameGame board
        *
        * @param rows number of board rows
        * @param cols number of board columns
        *
        * @param gravity direction in which tiles fall after a removal
        * possible values: 'down', 'up', 'left', 'right'
        *
        * @param mode game mode
        * 'normal'  -> removed tiles disappear permanently and empty lines are compacted
        * 'endless' -> removed tiles are replaced by new ones generated from the generator
        *
        * @param generator function used to generate new tile values
        * used for board initialization and for refilling tiles in endless mode
        *
        * @param ensurePlayable if true the initial board is guaranteed to contain
        * at least one removable region (size >= 2)
        *
        * @param equals comparator used to determine whether two tiles belong
        * to the same region
    */
    constructor(rows: number, columns: number, gravity: SameGameGravity, mode: SameGameMode, generator: () => T, ensurePlayable: boolean = false, equals: SameGameComparator<T> = (a: T | null, b: T | null): boolean => a === b) {
        this.rows = rows;
        this.cols = columns;
        this.gravity = gravity;
        this.mode = mode;
        this.generator = generator;
        this.equals = equals;
        this.flood = new FloodFill2D<T | null>();
        this.grid = [];
        for (let row: number = 0; row < rows; row++) {
            this.grid[row] = [];
        }
        if (ensurePlayable) {
            this.generatePlayableBoard(this.generator);
        }
        else {
            this.randomize(this.generator);
        }
    }

    /**
        * returns current board
    */
    public getGrid(): Grid2D<T | null> {
        return this.grid;
    }

    /**
    * returns the region starting from a given cell
    *
    * the region contains all orthogonally connected tiles that are
    * considered equal according to the comparator.
    *
    * @param row row index of the starting cell
    * @param col column index of the starting cell
    *
    * @returns list of cells belonging to the same region
    */
    public getRegion(row: number, col: number): SameGamePosition[] {
        if (!this.isInside(row, col)) {
            return [];
        }
        const value: T | null = this.grid[row][col];
        if (value === null) {
            return [];
        }
        const points: Point[] = this.flood.getConnectedRegion(this.grid, col, row, { equals: this.equals });
        const region: SameGamePosition[] = [];
        for (let i: number = 0; i < points.length; i++) {
            const p: Point = points[i];
            region.push({
                row: p.y,
                col: p.x
            });
        }
        return region;
    }

    /**
        * returns all removable regions
    */
    public getAllRegions(): SameGamePosition[][] {
        const visited: boolean[][] = [];
        for (let row: number = 0; row < this.rows; row++) {
            visited[row] = new Array(this.cols).fill(false);
        }
        const regions: SameGamePosition[][] = [];
        for (let row: number = 0; row < this.rows; row++) {
            for (let col: number = 0; col < this.cols; col++) {
                if (visited[row][col]) {
                    continue;
                }
                const value: T | null = this.grid[row][col];
                if (value === null) {
                    visited[row][col] = true;
                    continue;
                }
                const region: SameGamePosition[] = this.getRegion(row, col);
                for (let i: number = 0; i < region.length; i++) {
                    const cell: SameGamePosition = region[i];
                    visited[cell.row][cell.col] = true;
                }
                if (region.length >= 2) {
                    regions.push(region);
                }
            }
        }
        return regions;
    }

    /**
        * returns largest removable region
    */
    public getLargestRegion(): SameGamePosition[] {
        const regions: SameGamePosition[][] = this.getAllRegions();
        let largest: SameGamePosition[] = [];
        for (let i: number = 0; i < regions.length; i++) {
            if (regions[i].length > largest.length) {
                largest = regions[i];
            }
        }
        return largest;
    }

    /**
        * returns statistics about the current board
    */
    public getBoardStats(): SameGameBoardStats {
        let tiles: number = 0;
        let empty: number = 0;
        for (let row: number = 0; row < this.rows; row++) {
            for (let col: number = 0; col < this.cols; col++) {
                if (this.grid[row][col] === null) {
                    empty++;
                }
                else {
                    tiles++;
                }
            }
        }
        const regions: SameGamePosition[][] = this.getAllRegions();
        const largestRegion: number = regions.length > 0 ? Math.max(...regions.map(r => r.length)) : 0;
        const stats: SameGameBoardStats = {
            tiles: tiles,
            empty: empty,
            regions: regions,
            largestRegion: largestRegion
        };
        return stats;
    }

    /**
        * changes gravity direction
        *
        * @param gravity new gravity direction
        * @param instantApply if true the new gravity is immediately applied
        * and the board is compacted when in normal mode
    */
    public setGravity(gravity: SameGameGravity, instantApply: boolean = false): void {
        this.gravity = gravity;
        if (instantApply) {
            this.applyGravity();
            if (this.mode === 'normal') {
                this.compact();
            }
        }
    }

    /**
        * returns gravity direction
    */
    public getGravity(): SameGameGravity {
        return this.gravity;
    }

    /**
        * sets game mode
        *
        * @param mode game mode to use:
        * - 'normal' removed tiles disappear permanently
        * - 'endless' removed tiles are replaced by new generated ones
    */
    public setMode(mode: SameGameMode): void {
        this.mode = mode;
    }

    /**
        * returns current mode
    */
    public getMode(): SameGameMode {
        return this.mode;
    }

    /**
        * removes a region starting from the given coordinates and returns
        * a complete description of how the board changes as a result
        *
        * this method performs all core game steps in sequence:
        * - clears the selected region (if its size is >= 2)
        * - computes tile movements caused by gravity
        * - applies gravity to the board
        * - compacts rows or columns in normal mode
        * - refills empty cells in endless mode
        *
        * instead of only modifying the internal grid, it returns a structured
        * change object that can be used to drive animations, debugging tools,
        * or replay systems
        *
        * returned data includes:
        * - removed: tiles that were cleared
        * - moved: tiles displaced by gravity (per-tile movement)
        * - shifted: tiles moved during board compaction (row/column shifts)
        * - spawned: newly generated tiles (endless mode only)
        *
        * @param row row index of the starting cell
        * @param col column index of the starting cell
        * @returns a SameGameBoardChange object describing all board updates;
        * returns empty arrays if the region is not playable (size < 2)
    */
    public removeRegion(row: number, col: number): SameGameBoardChange<T> {
        const region: SameGamePosition[] = this.getRegion(row, col);
        if (region.length < 2) {
            return { removed: [], moved: [], shifted: [], spawned: [] };
        }
        const removed: SameGameBoardChange<T>['removed'] = [];
        for (const cell of region) {
            const value: T | null = this.grid[cell.row][cell.col];
            if (value !== null) {
                removed.push({
                    at: cell,
                    value: value
                });
            }
            this.grid[cell.row][cell.col] = null;
        }
        const moved = this.applyGravity();  
        let shifted: SameGameBoardChange<T>['shifted'] = [];
        let spawned: SameGameBoardChange<T>['spawned'] = [];
        if (this.mode === 'normal') {
            shifted = this.compact();
        }
        if (this.mode === 'endless') {
            spawned = this.refill();
        }
        return { removed, moved, shifted, spawned };
    }

    /**
        * returns true if any move exists
    */
    public hasMoves(): boolean {
        for (let row: number = 0; row < this.rows; row++) {
            for (let col: number = 0; col < this.cols; col++) {
                const value: T | null = this.grid[row][col];
                if (value === null) {
                    continue;
                }
                if (this.isInside(row + 1, col) && this.equals(this.grid[row + 1][col], value)) {
                    return true;
                }
                if (this.isInside(row, col + 1) && this.equals(this.grid[row][col + 1], value)) {
                    return true;
                }
            }
        }
        return false;
    }

    /**
        * returns the tile at the specified coordinates
        *
        * @param row row index of the cell
        * @param col column index of the cell
        * @returns the tile value at the given position, or null if the cell is empty
        * or the coordinates are outside the board
    */
    public getTile(row: number, col: number): T | null {
        return this.isInside(row, col) ? this.grid[row][col] : null;
    }

    /**
        * returns all non-empty tiles currently present on the board
        *
        * this method scans the entire grid and collects every tile
        * whose value is not null.
        *
        * the returned array contains the tile values (T) as stored
        * in the grid, preserving their current state.
        *
        * note:
        * - empty cells (null) are ignored
        * - the order is row-major (top to bottom, left to right)
        *
        * @returns array of all active tiles on the board
    */
    public getAllTiles(): T[] {
        const tiles: T[] = [];
        for (let row: number = 0; row < this.rows; row++) {
            for (let col: number = 0; col < this.cols; col++) {
                const value: T | null = this.grid[row][col];
                if (value !== null) {
                    tiles.push(value);
                }
            }
        }
        return tiles;
    }

    /**
        * sets the tile value at the specified coordinates
        *
        * @param row row index of the cell
        * @param col column index of the cell
        * @param value tile value to assign, or null to clear the cell
    */
    public setTile(row: number, col: number, value: T | null): void {
        if (this.isInside(row, col)) {
            this.grid[row][col] = value;
        }
    }

    /**
        * fills the entire grid using the provided generator function
        *
        * the generator is called once for each cell to produce a new tile value
        * and becomes the default generator used by the game (e.g. for refill)
        *
        * @param generator function used to generate tile values
    */
    public randomize(generator: () => T): void {
        this.generator = generator;
        for (let row: number = 0; row < this.rows; row++) {
            for (let col: number = 0; col < this.cols; col++) {
                this.grid[row][col] = generator();
            }
        }
    }

    /**
        * generates a random board that guarantees at least one playable move
        *
        * @param generator function used to generate tile values
    */
    public generatePlayableBoard(generator: () => T): void {
        this.randomize(generator);
        if (this.hasMoves()) {
            return;
        }
        const horizontal: boolean = Math.random() < 0.5;
        const value: T = generator();
        if (horizontal) {
            const i: number = Math.floor(Math.random() * (this.cols - 1));
            const j: number = Math.floor(Math.random() * this.rows);
            this.grid[j][i] = value;
            this.grid[j][i + 1] = value;
        }
        else {
            const i: number = Math.floor(Math.random() * this.cols);
            const j: number = Math.floor(Math.random() * (this.rows - 1));
            this.grid[j][i] = value;
            this.grid[j + 1][i] = value;
        }
    }

    /**
        * rotates the board 90 degrees clockwise
    */
    public rotateClockwise(): void {
        const newGrid: Grid2D<T | null> = [];
        for (let col: number = 0; col < this.cols; col++) {
            newGrid[col] = [];
            for (let row: number = 0; row < this.rows; row++) {
                newGrid[col][row] = this.grid[this.rows - 1 - row][col];
            }
        }
        const temp: number = this.rows;
        this.rows = this.cols;
        this.cols = temp;
        this.grid = newGrid;
    }

    /**
        * rotates the board 90 degrees counter-clockwise
    */
    public rotateCounterClockwise(): void {
        const newGrid: Grid2D<T | null> = [];
        for (let col: number = 0; col < this.cols; col++) {
            newGrid[col] = [];
            for (let row: number = 0; row < this.rows; row++) {
                newGrid[col][row] = this.grid[row][this.cols - 1 - col];
            }
        }
        const temp: number = this.rows;
        this.rows = this.cols;
        this.cols = temp;
        this.grid = newGrid;
    }

    /**
        * checks whether the given coordinates are inside the board boundaries
        *
        * @param row row index to validate
        * @param col column index to validate
        * @returns true if the coordinates are within the grid, false otherwise
    */
    private isInside(row: number, col: number): boolean {
        return row >= 0 && row < this.rows && col >= 0 && col < this.cols;
    }

    /**
        * applies gravity and returns tile movements
    */
    private applyGravity(): SameGameBoardChange<T>['moved'] {
        const moved: SameGameBoardChange<T>['moved'] = [];
        switch (this.gravity) {
            case 'down':
                for (let col: number = 0; col < this.cols; col++) {
                    let write: number = this.rows - 1;          
                    for (let row: number = this.rows - 1; row >= 0; row--) {
                        const value: T | null = this.grid[row][col];
                        if (value !== null) {
                            if (write !== row) {
                                moved.push({
                                    from: { row, col },
                                    to: { row: write, col },
                                    value: value
                                });
                                this.grid[write][col] = value;
                                this.grid[row][col] = null;
                            }
                            write--;
                        }
                    }
                }
                break;
            case 'up':
                for (let col: number = 0; col < this.cols; col++) {
                let write: number = 0;
                    for (let row: number = 0; row < this.rows; row++) {
                        const value: T | null = this.grid[row][col];
                        if (value !== null) {
                            if (write !== row) {
                                moved.push({
                                    from: { row, col },
                                    to: { row: write, col },
                                    value: value
                                });
                                this.grid[write][col] = value;
                                this.grid[row][col] = null;
                            }
                            write++;
                        }
                    }
                }
                break;
            case 'left':
                for (let row: number = 0; row < this.rows; row++) {
                    let write: number = 0;
                    for (let col: number = 0; col < this.cols; col++) {
                        const value: T | null = this.grid[row][col];
                        if (value !== null) {
                            if (write !== col) {
                                moved.push({
                                    from: { row, col },
                                    to: { row, col: write },
                                    value: value
                                });
                                this.grid[row][write] = value;
                                this.grid[row][col] = null;
                            }
                            write++;
                        }
                    }
                }
                break;
            case 'right':
                for (let row: number = 0; row < this.rows; row++) {
                    let write: number = this.cols - 1;
                    for (let col: number = this.cols - 1; col >= 0; col--) {
                        const value: T | null = this.grid[row][col];
                        if (value !== null) {
                            if (write !== col) {
                                moved.push({
                                    from: { row, col },
                                    to: { row, col: write },
                                    value: value
                                });
                                this.grid[row][write] = value;
                                this.grid[row][col] = null;
                            }
                            write--;
                        }
                    }
                }
                break;
        }
        return moved;
    }

    /**
        * compacts empty rows/columns and returns tile shifts
    */
    private compact(): SameGameBoardChange<T>['shifted'] {
        const shifted: SameGameBoardChange<T>['shifted'] = [];
        switch (this.gravity) {
            case 'down':
            case 'up':
                let writeCol: number = 0;
                for (let col: number = 0; col < this.cols; col++) {
                    let empty: boolean = true;
                    for (let row: number = 0; row < this.rows; row++) {
                        if (this.grid[row][col] !== null) {
                            empty = false;
                            break;
                        }
                    }
                    if (!empty) {
                        if (writeCol !== col) {
                            for (let row: number = 0; row < this.rows; row++) {
                                const value: T | null = this.grid[row][col];
                                if (value !== null) {
                                    shifted.push({
                                        from: { row, col },
                                        to: { row, col: writeCol },
                                        value: value
                                    });
                                    this.grid[row][writeCol] = value;
                                    this.grid[row][col] = null;
                                }
                            }
                        }
                        writeCol++;
                    }
                }
                break;
            case 'left':
            case 'right':
                let writeRow: number = 0;
                for (let row: number = 0; row < this.rows; row++) {
                    let empty: boolean = true;
                    for (let col: number = 0; col < this.cols; col++) {
                        if (this.grid[row][col] !== null) {
                            empty = false;
                            break;
                        }
                    }
                    if (!empty) {
                        if (writeRow !== row) {
                            for (let col: number = 0; col < this.cols; col++) {
                                const value: T | null = this.grid[row][col];
                                if (value !== null) {
                                    shifted.push({
                                        from: { row, col },
                                        to: { row: writeRow, col },
                                        value: value
                                    });
                                    this.grid[writeRow][col] = value;
                                    this.grid[row][col] = null;
                                }
                            }
                        }
                        writeRow++;
                    }
                }
                break;
        }
        return shifted;
    }

    /**
        * refills empty cells and returns spawned tiles
    */
    private refill(): SameGameBoardChange<T>['spawned'] {
        const spawned: SameGameBoardChange<T>['spawned'] = [];
        for (let row: number = 0; row < this.rows; row++) {
            for (let col: number = 0; col < this.cols; col++) {
                if (this.grid[row][col] === null) {
                    const value: T = this.generator();
                    this.grid[row][col] = value;
                    spawned.push({
                        at: { row, col },
                        value: value
                    });
                }
            }
        }
        return spawned;
    }
}